PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    SENHA TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS festa(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT,
    valor FLOAT,
    user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id)
);